import { User, Expense, Transaction } from "../types";

export const generateSummaryMessage = async (
  users: User[],
  expenses: Expense[],
  transactions: Transaction[],
): Promise<string> => {
  // Format data
  const userMap = new Map(users.map((u) => [u.id, u.name]));

  const totalSpent = expenses.reduce((sum, e) => sum + e.amount, 0);

  const transactionList = transactions
    .map(
      (t) =>
        `👉 ${userMap.get(t.fromId)} 給 (Pay) ${userMap.get(t.toId)}: $${t.amount.toFixed(2)}`,
    )
    .join("\n");

  const date = new Date().toLocaleDateString("zh-HK");

  const message = `
👋 各位，這是是次活動的數目總結 (${date})

💰 總支出 Total: $${totalSpent.toFixed(2)}

🧾 結算方案 (Who pays Whom):
${transactionList || "🎉 無需轉帳，條數已平！"}

記得 PayMe / FPS 俾返錢啦! 💸
Generated by 夾錢易 (EasySplit HK)
    `.trim();

  return message;
};
